name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  cocoapods:
    name: CocoaPods Lint
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s '/Applications/Xcode_11.4.app'
      - run: gem install bundler:1.17.3 && bundle install
      - run: ./test podspec
  
  xcode:
    name: Xcode ${{ matrix.xcode }} - ${{ matrix.platform }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11.4]
        platform: [macos, ios, tvos, macos_xcodespm, ios_xcodespm]
    steps:
    - uses: actions/checkout@v2
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: ./test ${{ matrix.platform }}

  swiftpm_darwin:
    name: SwiftPM, Darwin, Xcode ${{ matrix.xcode }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11.4]
    steps:
    - uses: actions/checkout@v2
    - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'
    - run: ./test swiftpm
